"""Initial migration

Revision ID: aa4e774dd6db
Revises: 01bb1e17a192
Create Date: 2024-06-22 13:26:27.423333

"""
from typing import Sequence, Union
import geoalchemy2

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa4e774dd6db'
down_revision: Union[str, None] = '01bb1e17a192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harmonized_landsat_sentinel_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('capture_date', sa.DateTime(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('b01_coastal_aerosol', sa.Float(), nullable=True),
    sa.Column('b02_blue', sa.Float(), nullable=True),
    sa.Column('b03_green', sa.Float(), nullable=True),
    sa.Column('b04_red', sa.Float(), nullable=True),
    sa.Column('b05_nir', sa.Float(), nullable=True),
    sa.Column('b06_swir1', sa.Float(), nullable=True),
    sa.Column('b07_swir2', sa.Float(), nullable=True),
    sa.Column('b08_nir_broad', sa.Float(), nullable=True),
    sa.Column('b8a_nir_narrow', sa.Float(), nullable=True),
    sa.Column('b09_water_vapor', sa.Float(), nullable=True),
    sa.Column('b10_cirrus', sa.Float(), nullable=True),
    sa.Column('b11_swir1', sa.Float(), nullable=True),
    sa.Column('b12_swir2', sa.Float(), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_harmonized_landsat_sentinel_data_location', 'harmonized_landsat_sentinel_data', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_harmonized_landsat_sentinel_data_capture_date'), 'harmonized_landsat_sentinel_data', ['capture_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harmonized_landsat_sentinel_data_capture_date'), table_name='harmonized_landsat_sentinel_data')
    op.drop_index('idx_harmonized_landsat_sentinel_data_location', table_name='harmonized_landsat_sentinel_data', postgresql_using='gist')
    op.drop_table('harmonized_landsat_sentinel_data')
    # ### end Alembic commands ###
